version: '3.8'

volumes:
  database-volume:
  app-volume:

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    restart: unless-stopped
    volumes:
      - app-volume:/var/www
    depends_on:
      - app
    container_name: nginx
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qara-http.entrypoints=http"
      - "traefik.http.routers.qara-http.rule=Host(`qara.42vienna.hackxit.com`)"
      - "traefik.http.routers.qara-http.middlewares=qara-https-redirect"
      - "traefik.http.middlewares.qara-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.qara-https-redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.qara.entrypoints=https"
      - "traefik.http.routers.qara.rule=Host(`qara.42vienna.hackxit.com`)"
      - "traefik.http.routers.qara.tls=true"
      - "traefik.http.routers.qara.tls.certresolver=cloudflare"
      - "traefik.http.services.qara.loadbalancer.server.port=80"
      - "traefik.http.routers.qara.middlewares=qara-headers"
      - "traefik.http.middlewares.qara-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.qara-headers.headers.customrequestheaders.X-Forwarded-Port=443"

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    restart: unless-stopped
    volumes:
      - app-volume:/var/www
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      APP_URL: ${APP_FULL_URL:-https://qara.42vienna.hackxit.com}
      DB_HOST: ${DB_CONTAINER_NAME:-mysqldb}
      DB_DATABASE: ${DB_NAME:-qara}
      DB_USERNAME: ${DB_USER:-qara}
      DB_PASSWORD: ${DB_PASS:-qarapass}
      DB_PORT: ${DB_PORT:-3306}
    container_name: app
    networks:
      - proxy

  mysqldb:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${DB_NAME:-qara}
      MYSQL_USER: ${DB_USER:-qara}
      MYSQL_PASSWORD: ${DB_PASS:-qarapass}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS:-root}
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    restart: unless-stopped
    volumes:
      - database-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "--password=${DB_ROOT_PASS:-root}"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 30
    container_name: ${DB_CONTAINER_NAME:-mysqldb}
    networks:
      - proxy

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: ${DB_CONTAINER_NAME:-mysqldb}
    depends_on:
      - mysqldb
    container_name: phpmyadmin
    networks:
      - proxy
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.phpmyadmin-http.entrypoints=http"
#      - "traefik.http.routers.phpmyadmin-http.rule=Host(`pma.42vienna.hackxit.com`)"
#      - "traefik.http.routers.phpmyadmin-http.middlewares=phpmyadmin-https-redirect"
#      - "traefik.http.middlewares.phpmyadmin-https-redirect.redirectscheme.scheme=https"
#      - "traefik.http.middlewares.phpmyadmin-https-redirect.redirectscheme.permanent=true"
#      - "traefik.http.routers.phpmyadmin.entrypoints=https"
#      - "traefik.http.routers.phpmyadmin.rule=Host(`pma.42vienna.hackxit.com`)"
#      - "traefik.http.routers.phpmyadmin.tls=true"
#      - "traefik.http.routers.phpmyadmin.tls.certresolver=cloudflare"
#      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
